# .github/actions/create-release/action.yml
name: 'Create Release'
description: 'Create a new GitHub release with artifacts'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get Package Version
      id: package-version
      shell: bash
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    
    - name: Create Tag
      id: create_tag
      shell: bash
      run: |
        TAG_NAME="v${{ steps.package-version.outputs.version }}"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        git tag $TAG_NAME
        git push origin $TAG_NAME
    
    - name: Generate Release Info
      id: release_info
      shell: bash
      run: |
        BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
        
        # 列出下载的构建产物
        echo "找到以下构建产物:"
        find artifacts -type f | sort
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.create_tag.outputs.tag_name }}
        name: Release ${{ steps.create_tag.outputs.tag_name }}
        body: |
          # 版本 ${{ steps.package-version.outputs.version }}
          构建时间: ${{ steps.release_info.outputs.build_date }}
        files: |
          artifacts/**/*.dmg
          artifacts/**/*.msi
          artifacts/**/*.deb
          artifacts/**/*.AppImage