# .github/actions/build-tauri/action.yml
name: 'Build Tauri App'
description: 'Build the Tauri application for different platforms'

inputs:
  os:
    description: 'Operating system'
    required: true
  rust-target:
    description: 'Rust target'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Tauri App (macOS)
      if: inputs.os == 'macOS'
      shell: bash
      run: |
        brew install create-dmg || true
        chmod +x src-tauri/build-aux/bundle_dmg.sh 2>/dev/null || true
        yarn tauri build --target $TAURI_TARGET
      env:
        CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: "true"
        RUST_BACKTRACE: "1"

    - name: Build Tauri App (Linux)
      if: inputs.os == 'Linux'
      shell: bash
      run: |
        export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
        # 安装javascriptcoregtk-4.1依赖
        sudo apt-get update
        sudo apt-get install -y libjavascriptcoregtk-4.1-dev
        # 确保javascriptcoregtk-4.1能被正确找到
        pkg-config --exists javascriptcoregtk-4.1 || echo "javascriptcoregtk-4.1 not found in PKG_CONFIG_PATH"
        yarn tauri build --target ${{ inputs.rust-target }}
      env:
        CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: "true"
        RUST_BACKTRACE: "1"
        WEBKIT_DISABLE_COMPOSITING_MODE: "1"

    - name: Build Tauri App (Windows)
      if: inputs.os == 'Windows'
      shell: bash
      run: |
        # 在构建前运行图标转换脚本（使用.cjs扩展名）
        node src-tauri/build-aux/convert_icon.cjs
        # 如果转换失败，尝试安装ImageMagick并重试
        if [ $? -ne 0 ] && command -v choco &> /dev/null; then
          echo "尝试安装ImageMagick并重试转换..."
          choco install imagemagick -y
          node src-tauri/build-aux/convert_icon.cjs
        fi
        yarn tauri build --target ${{ inputs.rust-target }}
      env:
        CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: "true"
        RUST_BACKTRACE: "1"