# .github/actions/process-artifacts/action.yml
name: 'Process Artifacts'
description: 'Process and rename build artifacts'

inputs:
  os:
    description: 'Operating system'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Package Version
      id: package-version
      shell: bash
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Rename Artifacts with Version
      shell: bash
      run: |
        VERSION="${{ steps.package-version.outputs.version }}"
        OS="${{ inputs.os }}"
        ARTIFACTS_DIR="src-tauri/target/release/bundle"
        
        case $OS in
          Linux)
            for file in $ARTIFACTS_DIR/deb/*.deb; do
              mv "$file" "${file%.deb}-$VERSION.deb"
            done
            for file in $ARTIFACTS_DIR/appimage/*.AppImage; do
              mv "$file" "${file%.AppImage}-$VERSION.AppImage"
            done
            ;;
          Windows)
            for file in $ARTIFACTS_DIR/msi/*.msi; do
              mv "$file" "${file%.msi}-$VERSION.msi"
            done
            ;;
          macOS)
            for file in $ARTIFACTS_DIR/dmg/*.dmg; do
              mv "$file" "${file%.dmg}-$VERSION.dmg"
            done
            ;;
        esac