name: Cross-Platform Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  NODE_OPTIONS: "--max-old-space-size=12288"

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust-target: x86_64-apple-darwin
          - os: windows-latest
            rust-target: x86_64-pc-windows-msvc
      fail-fast: false
      max-parallel: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Ubuntu专用依赖安装
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libgdk-pixbuf-2.0-dev \
          libwebkit2gtk-4.0-dev \
          libappindicator3-dev \
          libssl-dev \
          libx11-dev \
          libxi-dev

    - name: Setup Node.js with Yarn
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'

    - name: Update Vulnerable Dependencies
      run: |
        yarn add axios@^1.8.2
        yarn add @babel/runtime-corejs2@^7.26.10 @babel/runtime@^7.26.10
        yarn upgrade qiniu-js tiny-oss

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile --ignore-engines --production=false

    # 跨平台安全检查
    - name: Security Audit
      shell: bash
      run: |
        yarn audit --groups dependencies --level high
        AUDIT_RESULT=$?
        if [[ $AUDIT_RESULT -ge 16 ]]; then
          echo "::error::Critical vulnerabilities found!"
          exit 1
        elif [[ $AUDIT_RESULT -ge 8 ]]; then
          echo "::warning::Moderate vulnerabilities detected"
        fi

    # 构建优化步骤
    - name: Build application
      shell: bash
      run: |
        # macOS内存优化
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          export NODE_OPTIONS="--max-old-space-size=16384"
        fi

        # Vite构建命令兼容旧版本
        yarn build:only --mode production \
          --config vite.config.prod.ts \
          $(if [[ "$RUNNER_OS" == "macOS" ]]; then echo "--emptyOutDir"; fi)

        # Tauri构建
        yarn tauri build --target ${{ matrix.rust-target }}
      env:
        TAURI_PLATFORM: ${{ matrix.rust-target }}
        VITE_DROP_CONSOLE: "true"
        VITE_SOURCEMAP: "false"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}
        path: |
          src-tauri/target/release/*
          !src-tauri/target/release/*.d
        retention-days: 7

    # Windows专用清理
    - name: Windows Cleanup
      if: runner.os == 'Windows'
      run: |
        git config --system core.longpaths true
        Remove-Item -Recurse -Force node_modules -ErrorAction SilentlyContinue